### ISSUE TITLE
gv ls returns 'Moved Temporarily' error

### ISSUE THREAD

**Issue by stephenwithav** [matthewp/gv-app#3]
gv contacts works fine, but gv ls returns:

{ code: 100,
  message: 'UNKNOWN_FORMAT',
  details: 
   { res: 
      { _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        trailers: {},
        _pendings: [],
        _pendingIndex: 0,
        url: '',
        method: null,
        statusCode: 302,
        client: [Object],
        _consuming: true,
        _dumped: false,
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        upgrade: false,
        req: [Object],
        pipe: [Function],
        addListener: [Function],
        on: [Function],
        pause: [Function],
        resume: [Function],
        read: [Function],
        request: [Object],
        toJSON: [Function: toJSON],
        body: '<HTML>\n<HEAD>\n<TITLE>Moved Temporarily</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Moved Temporarily</H1>\nThe document has moved <A HREF="https://accounts.google.com/ServiceLogin?service=grandcentral&amp;passive=1209600&amp;continue=https://www.google.com/voice/m?[authinfo]&amp;followup=https://www.google.com/voice/m?[authinfo]">here</A>.\n</BODY>\n</HTML>\n' },
     body: '<HTML>\n<HEAD>\n<TITLE>Moved Temporarily</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Moved Temporarily</H1>\nThe document has moved <A HREF="https://accounts.google.com/ServiceLogin?service=grandcentral&amp;passive=1209600&amp;continue=https://www.google.com/voice/m?followup=https://www.google.com/voice/m?[authinfo]">here</A>.\n</BODY>\n</HTML>\n' },
  stack: 'Error\n    at Error.module.exports (/usr/local/lib/node_modules/gv/node_modules/voice.js/lib/voicejs.errors.js:7:16)\n    at Request._callback (/usr/local/lib/node_modules/gv/node_modules/voice.js/voice.js:242:12)\n    at Request.self.callback (/usr/local/lib/node_modules/gv/node_modules/voice.js/node_modules/request/index.js:148:22)\n    at Request.EventEmitter.emit (events.js:100:17)\n    at Request.<anonymous> (/usr/local/lib/node_modules/gv/node_modules/voice.js/node_modules/request/index.js:876:14)\n    at Request.EventEmitter.emit (events.js:119:20)\n    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/gv/node_modules/voice.js/node_modules/request/index.js:827:12)\n    at IncomingMessage.EventEmitter.emit (events.js:119:20)\n    at _stream_readable.js:910:16\n    at process._tickCallback (node.js:415:13)' }

**Comment by matthewp** [comment]
Thanks! Fixed.
